resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    [nginx]
    yandex_compute_instance.vm-1 ansible_ssh_host=${yandex_compute_instance.vm-1.network_interface.0.nat_ip_address} ansible_ssh_port=22
    DOC
  filename = "../ansible/inventory/prod.yml"



  depends_on = [
    yandex_compute_instance.vm-1
  ]
}